### ISSUE TITLE
Formatting question

### ISSUE THREAD

**Issue by dgleba** [yaph/chatgpt-export#2]
I pasted this input as a prompt:

![image](https://github.com/yaph/chatgpt-export/assets/4622715/fc1f910c-bc0a-40cb-b86b-9f86266ad1b1)

chatgpt-export output looked like this.

![image](https://github.com/yaph/chatgpt-export/assets/4622715/ad8e1448-5969-4ed9-907a-457c019968e2)

Is there a way to have the output more resemble the input?

**Comment by yaph** [comment]
I noticed this with my prompts too. I have no solution for this so far. As far as I know this only happens with prompts that use markdown formatting and not with responses. Not sure how to separate these cases cleanly though.

**Comment by dgleba** [comment]
Even if it is not markdown in the prompt, the output is altered.

My input:

In tensorflow 1.x I see this in the log:  '_save_checkpoints_secs': 600. 
How can I change the setting?

Output from  chatgpt2md:

PROMPT:
In tensorflow 1.x I see this in the log: '\_save\_checkpoints\_secs': 600. How can I change the setting?

**Comment by yaph** [comment]
Ok, looks like prompts need to be treated as plain text.

**Comment by yaph** [comment]
Prompts are now kept as they were entered.
